In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [3]:
ds=pd.read_csv("D:\\Internship\\Machine learning\\data-task-4.xlsx.csv")
print(ds)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [4]:
#import Ml libraries
!pip install scikit-learn

In [5]:
#to fill the empty values with mean
#SimpleImputer used for find simple mean
#fit_transform used to fill values
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values = np.nan, strategy= 'mean')
ds[["Age","Salary"]]= si.fit_transform(ds[["Age","Salary"]])
print(ds)

   Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes


In [6]:
#Encoding( OneHotEncoding)
#sparse_output used to output representation in binary 
from sklearn.preprocessing import OneHotEncoder
ohe= OneHotEncoder(sparse_output= False)
encoded_data = ohe.fit_transform(ds[["Country"]])
encoded_data

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [7]:
ds["Country"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [9]:
#get_feature_names_out used to add names of given column
column_names= ohe.get_feature_names_out(["Country"])
encoded_df=pd.DataFrame(encoded_data, columns = column_names)
encoded_df

Country_France  Country_Germany  Country_Spain
0             1.0              0.0            0.0
1             0.0              0.0            1.0
2             0.0              1.0            0.0
3             0.0              0.0            1.0
4             0.0              1.0            0.0
5             1.0              0.0            0.0
6             0.0              0.0            1.0
7             1.0              0.0            0.0
8             0.0              1.0            0.0
9             1.0              0.0            0.0

In [10]:
#join it to original dataset
ds=pd.concat([ds,encoded_df],axis=1)
print(ds)


   Country        Age        Salary Purchased  Country_France  \
0   France  44.000000  72000.000000        No             1.0   
1    Spain  27.000000  48000.000000       Yes             0.0   
2  Germany  30.000000  54000.000000        No             0.0   
3    Spain  38.000000  61000.000000        No             0.0   
4  Germany  40.000000  63777.777778       Yes             0.0   
5   France  35.000000  58000.000000       Yes             1.0   
6    Spain  38.777778  52000.000000        No             0.0   
7   France  48.000000  79000.000000       Yes             1.0   
8  Germany  50.000000  83000.000000        No             0.0   
9   France  37.000000  67000.000000       Yes             1.0   

   Country_Germany  Country_Spain  
0              0.0            0.0  
1              0.0            1.0  
2              1.0            0.0  
3              0.0            1.0  
4              1.0            0.0  
5              0.0            0.0  
6              0.0            1.

In [11]:
#Drop previous columns which are now not necessary
ds=ds.drop(columns=["Country"])
print(ds)

         Age        Salary Purchased  Country_France  Country_Germany  \
0  44.000000  72000.000000        No             1.0              0.0   
1  27.000000  48000.000000       Yes             0.0              0.0   
2  30.000000  54000.000000        No             0.0              1.0   
3  38.000000  61000.000000        No             0.0              0.0   
4  40.000000  63777.777778       Yes             0.0              1.0   
5  35.000000  58000.000000       Yes             1.0              0.0   
6  38.777778  52000.000000        No             0.0              0.0   
7  48.000000  79000.000000       Yes             1.0              0.0   
8  50.000000  83000.000000        No             0.0              1.0   
9  37.000000  67000.000000       Yes             1.0              0.0   

   Country_Spain  
0            0.0  
1            1.0  
2            0.0  
3            1.0  
4            0.0  
5            0.0  
6            1.0  
7            0.0  
8            0.0  
9     

In [12]:
#labelEncoder encode target labels with value between 0 and 1_classes-1
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ds["Purchased"] = le.fit_transform(ds["Purchased"])
ds

Age        Salary  Purchased  Country_France  Country_Germany  \
0  44.000000  72000.000000          0             1.0              0.0   
1  27.000000  48000.000000          1             0.0              0.0   
2  30.000000  54000.000000          0             0.0              1.0   
3  38.000000  61000.000000          0             0.0              0.0   
4  40.000000  63777.777778          1             0.0              1.0   
5  35.000000  58000.000000          1             1.0              0.0   
6  38.777778  52000.000000          0             0.0              0.0   
7  48.000000  79000.000000          1             1.0              0.0   
8  50.000000  83000.000000          0             0.0              1.0   
9  37.000000  67000.000000          1             1.0              0.0   

   Country_Spain  
0            0.0  
1            1.0  
2            0.0  
3            1.0  
4            0.0  
5            0.0  
6            1.0  
7            0.0  
8            0.0  
9            0.0

In [13]:
# OrdinalEncoder
from sklearn.preprocessing import OrdinalEncoder

# Sample data: Categorical features with an inherent order
data = [['Medium'],['High'], ['Low'], ['Medium'], ['High'], ['Medium'], ['Low'], ['Low']]

# Initialize the OrdinalEncoder
encoder = OrdinalEncoder(categories=[[ 'High', 'Medium', 'Low']])  # Define the order explicitly

# Fit and transform the data
encoded_data = encoder.fit_transform(data)

# Display the encoded data
print("Original Data:", data)
print("Encoded Data:\n", encoded_data)

Original Data: [['Medium'], ['High'], ['Low'], ['Medium'], ['High'], ['Medium'], ['Low'], ['Low']]
Encoded Data:
 [[1.]
 [0.]
 [2.]
 [1.]
 [0.]
 [1.]
 [2.]
 [2.]]


In [14]:
#Feature scaling
#StandardScaler - standerdize features by removing the mean and scaling to unit variance
#Uses formula: z = (x-u) / s
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
ds[["Age","Salary"]] = sc.fit_transform(ds[["Age","Salary"]])
ds

Age        Salary  Purchased  Country_France  Country_Germany  \
0  0.758874  7.494733e-01          0             1.0              0.0   
1 -1.711504 -1.438178e+00          1             0.0              0.0   
2 -1.275555 -8.912655e-01          0             0.0              1.0   
3 -0.113024 -2.532004e-01          0             0.0              0.0   
4  0.177609  6.632192e-16          1             0.0              1.0   
5 -0.548973 -5.266569e-01          1             1.0              0.0   
6  0.000000 -1.073570e+00          0             0.0              0.0   
7  1.340140  1.387538e+00          1             1.0              0.0   
8  1.630773  1.752147e+00          0             0.0              1.0   
9 -0.258340  2.937125e-01          1             1.0              0.0   

   Country_Spain  
0            0.0  
1            1.0  
2            0.0  
3            1.0  
4            0.0  
5            0.0  
6            1.0  
7            0.0  
8            0.0  
9            0.0

In [15]:
# sc.scale_ tells us the standard deviation of each feature in the original data. 
# These values are used by StandardScaler to scale each value to unit variance.
sc.scale_

array([6.8815373e+00, 1.0970668e+04])

In [16]:
sc.mean_

array([3.87777778e+01, 6.37777778e+04])

In [17]:
sc.transform([[27,48000]])

C:\Users\Sri\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.71150388, -1.43817841]])

In [18]:
sc.inverse_transform([[-1.71150388, -1.43817841]])

array([[2.7e+01, 4.8e+04]])

In [19]:
#Dividind dataset into dependent(output varb) and independent(i/p varb) variables
X = ds[["Age","Salary","Country_France","Country_Germany","Country_Spain"]]
y = ds[["Purchased"]]

In [20]:
y

Purchased
0          0
1          1
2          0
3          0
4          1
5          1
6          0
7          1
8          0
9          1

In [21]:
#Dividing dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 1)
# This fixes the randomness, so you and others always get the same split every time you run the code.

In [23]:
X_train

Age        Salary  Country_France  Country_Germany  Country_Spain
6  0.000000 -1.073570e+00             0.0              0.0            1.0
4  0.177609  6.632192e-16             0.0              1.0            0.0
0  0.758874  7.494733e-01             1.0              0.0            0.0
3 -0.113024 -2.532004e-01             0.0              0.0            1.0
1 -1.711504 -1.438178e+00             0.0              0.0            1.0
7  1.340140  1.387538e+00             1.0              0.0            0.0
8  1.630773  1.752147e+00             0.0              1.0            0.0
5 -0.548973 -5.266569e-01             1.0              0.0            0.0

In [24]:
X_train

Age        Salary  Country_France  Country_Germany  Country_Spain
6  0.000000 -1.073570e+00             0.0              0.0            1.0
4  0.177609  6.632192e-16             0.0              1.0            0.0
0  0.758874  7.494733e-01             1.0              0.0            0.0
3 -0.113024 -2.532004e-01             0.0              0.0            1.0
1 -1.711504 -1.438178e+00             0.0              0.0            1.0
7  1.340140  1.387538e+00             1.0              0.0            0.0
8  1.630773  1.752147e+00             0.0              1.0            0.0
5 -0.548973 -5.266569e-01             1.0              0.0            0.0

In [25]:
y_train

Purchased
6          0
4          1
0          0
3          0
1          1
7          1
8          0
5          1

In [22]:
y_test

Purchased
2          0
9          1